### ISSUE TITLE
doesn't run on non-darwin machines

### ISSUE THREAD

**Issue by sleungcy** [zertosh/dep-case-verify#4]
I have a linux VM running on a file system that isn't case-sensitive. The plugin currently does not do anything if isDarwin is false. Can we remove that isDarwin check?

**Comment by tomyf** [comment]
I just ran into the same problem, for a Windows environment. Maybe the check `isDarwin` should also allow `win32` ? 

See NodeJS doc : https://nodejs.org/api/process.html#process_process_platform

**Comment by zertosh** [comment]
dep-case-verify@2.1.0 no longer has the OS check.

**Comment by tomyf** [comment]
It's now working for me, thank you !
